Repository Strong-Potato/TripVote-BE, pull requests merged in 2024-01, with the labels that each got.

#18 [Feat] 응답 형식 및 에러 핸들링
  app/src/main/java/fc/be/exception/ApplicationException.java
  app/src/main/java/fc/be/global/exception/BizException.java
  app/src/main/java/fc/be/global/exception/ExternalServiceErrorCode.java
  app/src/main/java/fc/be/global/exception/ExternalServiceException.java
  app/src/main/java/fc/be/global/exception/GlobalExceptionHandler.java
  app/src/main/java/fc/be/global/http/ApiResponse.java
  app/src/main/resources/docs/response-flow.jpg
Labels: enhancement, good first issue

#27 [Refactor] 프로젝트 구조 조정
  app/src/main/java/fc/be/domain/place/Location.java
  app/src/main/java/fc/be/domain/place/Place.java
  app/src/main/java/fc/be/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/domain/place/entity/Accommodation.java
  app/src/main/java/fc/be/domain/place/entity/Facility.java
  app/src/main/java/fc/be/domain/place/entity/Festival.java
  app/src/main/java/fc/be/domain/place/entity/Leports.java
  app/src/main/java/fc/be/domain/place/entity/Restaurant.java
  app/src/main/java/fc/be/domain/place/entity/Shop.java
  app/src/main/java/fc/be/domain/place/entity/Spot.java
  app/src/main/java/fc/be/domain/place/service/PlaceService.java
  app/src/main/java/fc/be/global/util/ContentTypeIdConverter.java
  app/src/main/java/fc/be/global/util/ListImagesConverter.java
  openapi/build.gradle
  openapi/src/main/java/fc/be/domain/place/service/PlaceService.java
  openapi/src/main/java/fc/be/tourapi/TourAPIService.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/AccommodationDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/FacilityDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/FestivalDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/LeportsDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/LocationDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/PlaceDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/RestaurantDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/ShopDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/bone/SpotDTO.java
  openapi/src/main/java/fc/be/tourapi/dto/mapper/AreaBasedSyncMapper.java
  openapi/src/main/java/fc/be/tourapi/dto/mapper/DetailCommonMapper.java
  openapi/src/main/java/fc/be/tourapi/dto/mapper/DetailIntroMapper.java
  openapi/src/main/java/fc/be/tourapi/dto/mapper/SearchKeywordMapper.java
  openapi/src/main/java/fc/be/tourapi/dto/mapper/TourAPIMapper.java
  openapi/src/main/java/fc/be/tourapi/tools/ObjectMerger.java
  openapi/src/main/java/fc/be/tourapi/tools/TourAPIDomainConverter.java
Labels: enhancement

#36 [Feat] Place 기능 구현 - 상세 정보
  app/src/main/java/fc/be/app/domain/place/Place.java
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoGetResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertRequest.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertResponse.java
  app/src/main/java/fc/be/app/domain/place/exception/PlaceErrorCode.java
  app/src/main/java/fc/be/app/domain/place/exception/PlaceException.java
  app/src/main/java/fc/be/app/domain/place/repository/PlaceRepository.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  build.gradle
  openapi/build.gradle
  openapi/src/main/java/fc/be/openapi/tourapi/TourAPIService.java
  openapi/src/main/java/fc/be/openapi/tourapi/constant/ContentTypeId.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/bone/PlaceDTO.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/AreaBasedSyncMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/DetailCommonMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/DetailIntroMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/SearchKeywordMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/ErrorMessage.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/NoItemsFromAPIException.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/ProblemDetailCreator.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/TourAPIError.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/TourAPIErrorCode.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/TourAPIErrorMessage.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/TourAPIExceptionHandler.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/WrongRequestException.java
  openapi/src/main/java/fc/be/openapi/tourapi/exception/WrongXMLFormatException.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/ErrorMessageLoader.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/ObjectMerger.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/TourAPICommunicator.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/TourAPIDomainConverter.java
  openapi/src/main/resources/error-openapi.yml
  openapi/src/test/http/http-client.env.json
  openapi/src/test/http/place.http
  openapi/src/test/test/http/place.http
Labels: documentation

#37 [Feat] Place 기능 구현 - 검색 기능
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceSearchResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  openapi/src/main/java/fc/be/openapi/tourapi/TourAPIService.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/TourAPICommunicator.java
  openapi/src/test/http/place.http
Labels: enhancement

#38 [Feat] Place 기능 구현 - 주변 장소 추천
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceNearbyResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  openapi/src/main/resources/popular-places.json
  openapi/src/test/http/place.http
Labels: enhancement

#39 Revert "[Feat] Place 기능 구현 - 주변 장소 추천"
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceNearbyResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  openapi/src/main/resources/popular-places.json
  openapi/src/test/http/place.http
Labels: invalid

#41 [Feat] Place 기능 구현 - 인기 장소 추천
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  openapi/src/main/resources/popular-places.json
Labels: enhancement

#43 [Feature] 소셜 로그인 구현
  app/build.gradle
  app/src/main/java/fc/be/app/domain/member/entity/Member.java
  app/src/main/java/fc/be/app/domain/member/repository/MemberRepository.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommand.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommandHandler.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQuery.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQueryHandler.java
  app/src/main/java/fc/be/app/domain/member/vo/AuthProvider.java
  app/src/main/java/fc/be/app/global/config/security/SecurityAppConfig.java
  app/src/main/java/fc/be/app/global/config/security/converter/Converter.java
  app/src/main/java/fc/be/app/global/config/security/converter/DelegatingProviderUserConverter.java
  app/src/main/java/fc/be/app/global/config/security/converter/OAuth2KakaoUserConverter.java
  app/src/main/java/fc/be/app/global/config/security/converter/OidcKakaoUserConverter.java
  app/src/main/java/fc/be/app/global/config/security/converter/ProviderUserConvertRequest.java
  app/src/main/java/fc/be/app/global/config/security/exception/UnsupportedProviderException.java
  app/src/main/java/fc/be/app/global/config/security/model/KakaoOidcUser.java
  app/src/main/java/fc/be/app/global/config/security/model/KakaoUser.java
  app/src/main/java/fc/be/app/global/config/security/model/OAuth2ProviderUser.java
  app/src/main/java/fc/be/app/global/config/security/model/ProviderUser.java
  app/src/main/java/fc/be/app/global/config/security/provider/AuthenticationDetails.java
  app/src/main/java/fc/be/app/global/config/security/service/AbstractOAuth2UserService.java
  app/src/main/java/fc/be/app/global/config/security/service/CustomOAuth2UserService.java
  app/src/main/java/fc/be/app/global/config/security/service/CustomOidcUserService.java
  app/src/main/java/fc/be/app/global/util/FlattenMapUtils.java
Labels: enhancement

#46 [Feat/Test/Chore] Space Entity 기준하에 기능 구현
  app/build.gradle
  app/src/main/java/fc/be/TripVoteApplication.java
  app/src/main/java/fc/be/app/domain/member/exception/MemberErrorCode.java
  app/src/main/java/fc/be/app/domain/member/exception/MemberException.java
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/UpdateSpaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/JoinedMember.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceException.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustom.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/space/vo/SpaceType.java
  app/src/main/java/fc/be/app/global/config/QueryDslConfig.java
  app/src/main/java/fc/be/app/global/config/WebConfig.java
  app/src/main/java/fc/be/app/global/config/security/SecurityConfig.java
  app/src/main/java/fc/be/app/global/util/SpaceTypeRequestConverter.java
  app/src/test/java/fc/be/app/config/TestQueryDslConfig.java
  app/src/test/java/fc/be/app/domain/space/controller/SpaceControllerTest.java
  app/src/test/java/fc/be/app/domain/space/entity/SpaceTest.java
  app/src/test/java/fc/be/app/domain/space/repository/SpaceRepositoryTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
  app/src/test/resources/application-test.yml
Labels: enhancement

#48 [Feat] 찜(Wish) 구현
  app/src/main/java/fc/be/app/domain/place/Place.java
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoGetResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertRequest.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceSearchResponse.java
  app/src/main/java/fc/be/app/domain/place/entity/Accommodation.java
  app/src/main/java/fc/be/app/domain/place/entity/Facility.java
  app/src/main/java/fc/be/app/domain/place/entity/Festival.java
  app/src/main/java/fc/be/app/domain/place/entity/Leports.java
  app/src/main/java/fc/be/app/domain/place/entity/Restaurant.java
  app/src/main/java/fc/be/app/domain/place/entity/Shop.java
  app/src/main/java/fc/be/app/domain/place/entity/Spot.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  app/src/main/java/fc/be/app/domain/wish/controller/WishController.java
  app/src/main/java/fc/be/app/domain/wish/dto/WishAddRequest.java
  app/src/main/java/fc/be/app/domain/wish/dto/WishAddResponse.java
  app/src/main/java/fc/be/app/domain/wish/dto/WishGetResponse.java
  app/src/main/java/fc/be/app/domain/wish/entity/Wish.java
  app/src/main/java/fc/be/app/domain/wish/entity/WishId.java
  app/src/main/java/fc/be/app/domain/wish/repository/WishRepository.java
  app/src/main/java/fc/be/app/domain/wish/service/WishService.java
  app/src/main/java/fc/be/app/global/config/jpa/JpaAuditConfig.java
  app/src/main/resources/application-dev.yml
  app/src/test/http/http-client.env.json
  app/src/test/http/wish.http
  openapi/src/main/java/fc/be/openapi/tourapi/dto/bone/PlaceDTO.java
Labels: enhancement

#54 [Feat] TourAPI 카테고리 별 검색
  app/src/main/java/fc/be/app/domain/place/Place.java
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceNearbyResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceSearchResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  app/src/test/http/http-client.env.json
  openapi/src/main/java/fc/be/openapi/config/TourAPIProperties.java
  openapi/src/main/java/fc/be/openapi/tourapi/TourAPIService.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/bone/LocationDTO.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/bone/PlaceDTO.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/AreaBasedSyncMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/DetailCommonMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/SearchKeywordMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/TourAPICommunicator.java
  openapi/src/main/resources/popular-places.json
  openapi/src/test/http/http-client.env.json
  openapi/src/test/http/place.http
Labels: enhancement

#58 [Feat] Review Entity 기능 구현 (1/3)
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertRequest.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoInsertResponse.java
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewCreateRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewCreateResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewEditRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewEditResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetResponse.java
  app/src/main/java/fc/be/app/domain/review/entity/Review.java
  app/src/main/java/fc/be/app/domain/review/exception/ReviewErrorCode.java
  app/src/main/java/fc/be/app/domain/review/exception/ReviewException.java
  app/src/main/java/fc/be/app/domain/review/repository/ReviewRepository.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  app/src/main/java/fc/be/app/domain/space/entity/Candidate.java
  app/src/test/http/review.http
Labels: enhancement

#60 [Feat] Review Entity 기능 구현 (2/3)
  build.gradle
  openapi/src/main/java/fc/be/openapi/config/OpenFeignConfig.java
  openapi/src/main/java/fc/be/openapi/google/GooglePlacesClient.java
  openapi/src/main/java/fc/be/openapi/google/GooglePlacesService.java
  openapi/src/main/java/fc/be/openapi/google/ReviewJsonReader.java
  openapi/src/main/java/fc/be/openapi/google/SearchJsonReader.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/GoogleReviewResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/GoogleTempRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/GoogleTempReviewResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/AuthorAttribution.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/GoogleConverter.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/GoogleRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/OriginalText.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/Review.java
  openapi/src/main/java/fc/be/openapi/google/dto/search/GoogleSearchResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/search/form/Place.java
  openapi/src/main/resources/application-openapi.yml
  openapi/src/main/resources/google-review.json
  openapi/src/main/resources/google-search.json
  openapi/src/main/resources/review-example/rating/place_rating_12.json
  openapi/src/main/resources/review-example/rating/place_rating_14.json
  openapi/src/main/resources/review-example/rating/place_rating_15.json
  openapi/src/main/resources/review-example/rating/place_rating_28.json
  openapi/src/main/resources/review-example/rating/place_rating_32.json
  openapi/src/main/resources/review-example/rating/place_rating_38.json
  openapi/src/main/resources/review-example/rating/place_rating_39.json
  openapi/src/main/resources/review-example/reviews/place_12.json
  openapi/src/main/resources/review-example/reviews/place_14.json
  openapi/src/main/resources/review-example/reviews/place_15.json
  openapi/src/main/resources/review-example/reviews/place_28.json
  openapi/src/main/resources/review-example/reviews/place_32.json
  openapi/src/main/resources/review-example/reviews/place_38.json
  openapi/src/main/resources/review-example/reviews/place_39.json
Labels: enhancement

#57 [Feat] Journey 기능 구현
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/JoinedMember.java
  app/src/main/java/fc/be/app/domain/space/entity/Journey.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/JourneyRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/test/java/fc/be/app/domain/space/entity/JourneyTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#61 [Feat] Review Entity 기능 구현 (3/3)
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewCreateRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewEditRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetMemberResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewRatingResponse.java
  app/src/main/java/fc/be/app/domain/review/exception/ReviewErrorCode.java
  app/src/main/java/fc/be/app/domain/review/repository/ReviewRepository.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
  openapi/src/main/java/fc/be/openapi/google/ReviewJsonReader.java
  openapi/src/test/http/review.http
Labels: enhancement

#63 [Refactor] 투표 도메인 분리
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/entity/VotedMember.java
Labels: enhancement

#67 [bugfix] JpaQueryFactory Bean 중복 제거
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/global/config/QueryDslConfig.java
  app/src/test/java/fc/be/app/config/TestQueryDslConfig.java
  app/src/test/java/fc/be/app/domain/space/repository/SpaceRepositoryTest.java
Labels: bug

#65 Feature/#21 token authentication
  app/build.gradle
  app/src/main/java/fc/be/app/global/config/RedisConfig.java
  app/src/main/java/fc/be/app/global/config/security/SecurityAppConfig.java
  app/src/main/java/fc/be/app/global/config/security/SecurityConfig.java
  app/src/main/java/fc/be/app/global/config/security/exception/InvalidJwtException.java
  app/src/main/java/fc/be/app/global/config/security/filter/JwtAuthenticationFilter.java
  app/src/main/java/fc/be/app/global/config/security/handler/LoginAuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/config/security/handler/OAuth2AuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/config/security/model/token/JwtAuthenticationToken.java
  app/src/main/java/fc/be/app/global/config/security/model/token/RefreshToken.java
  app/src/main/java/fc/be/app/global/config/security/model/token/TokenPair.java
  app/src/main/java/fc/be/app/global/config/security/properties/TokenProperties.java
  app/src/main/java/fc/be/app/global/config/security/provider/JwtAuthenticationProvider.java
  app/src/main/java/fc/be/app/global/config/security/service/RefreshTokenService.java
  app/src/main/java/fc/be/app/global/util/CookieUtil.java
  app/src/main/java/fc/be/app/global/util/JwtService.java
  app/src/main/resources/application-dev.yml
  app/src/main/resources/application-prod.yml
  app/src/test/resources/application-test.yml
Labels: enhancement, good first issue

#72 [Feat] block된 email의 잔여시간 응답 추가
  app/src/main/java/fc/be/app/domain/member/dto/CheckTokenRequest.java
  app/src/main/java/fc/be/app/domain/member/dto/LoginRequest.java
  app/src/main/java/fc/be/app/domain/member/dto/RegisterRequest.java
  app/src/main/java/fc/be/app/domain/member/dto/SendEmailRequest.java
  app/src/main/java/fc/be/app/domain/member/exception/AuthException.java
  app/src/main/java/fc/be/app/domain/member/provider/TokenProvider.java
  app/src/main/java/fc/be/app/global/exception/BizException.java
Labels: enhancement

#70 [Feat/Fix] 여행 기능 추가 및 여정 로직 수정
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/DateUpdateRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/TitleUpdateRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/UpdateSpaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneysResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpacesResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/Journey.java
  app/src/main/java/fc/be/app/domain/space/entity/SelectedPlace.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/repository/JourneyRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SelectedPlaceRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/test/java/fc/be/app/domain/space/controller/SpaceControllerTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#76 [Fix/Refactor] 여정과 여행등록에 대한 리펙토링
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/DateUpdateRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/TitleUpdateRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneysResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpacesResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/JoinedMember.java
  app/src/main/java/fc/be/app/domain/space/entity/Journey.java
  app/src/main/java/fc/be/app/domain/space/entity/SelectedPlace.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/JourneyRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SelectedPlaceRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustom.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#80 [Feat/Refactor] 회원 관련 조회 api 통합 및 구현
  app/src/main/java/fc/be/app/domain/member/controller/MemberController.java
  app/src/main/java/fc/be/app/domain/member/dto/response/MyInfoResponse.java
  app/src/main/java/fc/be/app/domain/member/dto/response/MyPlacesResponse.java
  app/src/main/java/fc/be/app/domain/member/dto/response/MyReviewsResponse.java
  app/src/main/java/fc/be/app/domain/member/dto/response/MySpacesResponse.java
  app/src/main/java/fc/be/app/domain/member/repository/MemberRepository.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQuery.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQueryHandler.java
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/review/dto/response/ReviewResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/response/ReviewsResponse.java
  app/src/main/java/fc/be/app/domain/review/repository/ReviewRepository.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpacesResponse.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustom.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/wish/dto/WishGetResponse.java
  app/src/main/java/fc/be/app/domain/wish/repository/WishRepository.java
  app/src/main/java/fc/be/app/domain/wish/service/WishService.java
  app/src/test/java/fc/be/app/domain/member/repository/MemberRepositoryTest.java
  app/src/test/java/fc/be/app/domain/member/service/MemberCommandHandlerTest.java
  app/src/test/java/fc/be/app/domain/member/service/MemberQueryHandlerTest.java
  app/src/test/java/fc/be/app/domain/space/repository/SpaceRepositoryTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#82 [feat] 투표 생성 기능 추가
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/VoteCreateApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteException.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteManageUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#85 [feat] 투표 후보 추가 기능 추가
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/CandidateAddApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/dto/MemberProfile.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepositoryCustom.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteInfoQueryUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteManageUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#93 [Feat] 회원은 본인이 속한 스페이스에 투표를 생성할 수 있다.
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/VoteCreateApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteException.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteManageUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#94 [Feat] 스페이스 회원은 투표의 후보를 추가할 수 있다.
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/CandidateAddApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/dto/MemberProfile.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteInfoQueryUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteManageUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#96 [Feat] #86 여행스페이스 조회 시 초대멤버 정보 함께 조회
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
Labels: enhancement

#98 [Feat] 후보에 회원 정보 추가.
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/service/VoteInfoQueryUseCase.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#102 [Feat] S3 PreSigned 기능 추가
  app/build.gradle
  app/src/main/java/fc/be/app/global/s3/api/S3Controller.java
  app/src/main/java/fc/be/app/global/s3/config/S3Config.java
  app/src/main/java/fc/be/app/global/s3/service/CreatePreSignedUrlUseCase.java
  app/src/main/java/fc/be/app/global/s3/service/FakeS3Service.java
  app/src/main/java/fc/be/app/global/s3/service/S3Service.java
Labels: enhancement

#104 [Bugfix] ApiResponse에 제네릭을 추가한다.
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/global/http/ApiResponse.java
Labels: bug

#116 [Feat] 여행 스페이스 권한체크 및 방어코드 추가
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#117 [Feat] Review Entity 코드 리팩토링
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetResponse.java
  app/src/main/java/fc/be/app/domain/review/repository/ReviewRepository.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  app/src/test/http/http-client.env.json
  app/src/test/http/review.http
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
  openapi/src/main/java/fc/be/openapi/config/OpenFeignConfig.java
  openapi/src/main/java/fc/be/openapi/google/.gitkeep
  openapi/src/main/java/fc/be/openapi/google/ReviewJsonReader.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIReviewResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/GoogleTempRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/GoogleTempReviewResponse.java
  openapi/src/main/java/fc/be/openapi/google/service/GooglePlacesClient.java
  openapi/src/main/java/fc/be/openapi/google/service/GoogleReviewService.java
  openapi/src/main/java/fc/be/openapi/google/service/JsonReviewService.java
  openapi/src/main/java/fc/be/openapi/google/service/ReviewAPIService.java
Labels: enhancement

#118 [Feat] 이메일 검증 템플릿 기능 구현
  app/src/main/java/fc/be/app/domain/member/controller/AuthController.java
  app/src/main/java/fc/be/app/global/exception/InternalServiceErrorCode.java
  app/src/main/java/fc/be/app/global/exception/InternalServiceException.java
  app/src/main/java/fc/be/app/global/mail/service/MailService.java
  app/src/main/resources/templates/mail-template.html
Labels: enhancement

#122 [Feat] Place 별점 추가
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceNearbyResponse.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#126 [Fix] AWS SES 의존성 제거
  app/build.gradle
  app/src/main/java/fc/be/app/global/config/mail/MailConfig.java
  app/src/main/java/fc/be/app/global/mail/service/MailService.java
  app/src/test/resources/application-test.yml
Labels: invalid

#127 [Feat] Review Service Test 코드 작성
  app/src/test/java/fc/be/app/domain/review/unit/ReviewDTOFixture.java
  app/src/test/java/fc/be/app/domain/review/unit/ReviewFixture.java
  app/src/test/java/fc/be/app/domain/review/unit/ReviewServiceTest.java
Labels: enhancement

#133 [Feat] Space Policy 설정 추가 구현
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/Journey.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/test/java/fc/be/app/domain/space/controller/SpaceControllerTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#130 [Build] Gradle 내 Swaggerhub 추가
  app/build.gradle
Labels: enhancement

#129 [Feat] Place 인기여행지 개편
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetRequest.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularGetResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  app/src/main/java/fc/be/app/global/exception/GlobalExceptionHandler.java
  openapi/src/main/java/fc/be/openapi/config/TourAPIProperties.java
  openapi/src/main/resources/popular-places.json
Labels: enhancement

#137 [Feat] local용 Cookie 발급
  app/src/main/java/fc/be/app/global/config/security/filter/JwtAuthenticationFilter.java
  app/src/main/java/fc/be/app/global/config/security/handler/LoginAuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/config/security/handler/OAuth2AuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/util/CookieUtil.java
Labels: bug

#139 [Feat] 여행스페이스 방문기록 처리 및 최근 방문한 여행스페이스 접근 기능 구현
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceIdResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/JoinedMember.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceTokenService.java
  app/src/main/java/fc/be/app/domain/space/vo/SpaceToken.java
  app/src/main/java/fc/be/app/global/config/RedisConfig.java
  app/src/main/java/fc/be/app/global/config/WebConfig.java
  app/src/main/java/fc/be/app/global/filter/SpaceOncePerRequestFilter.java
  app/src/main/java/fc/be/app/global/interceptor/SpaceInterceptor.java
  app/src/test/java/fc/be/app/domain/space/controller/SpaceControllerTest.java
Labels: enhancement

#144 [Feat] 투표 결과를 본 여부 상태값 저장
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/report-bug.md
  .github/pull_request_template.md
  .gitignore
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/entity/VoteResultMember.java
  app/src/main/java/fc/be/app/domain/vote/exception/VoteErrorCode.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteResultMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VotedMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VoteResultResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VotesResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#140 [Feat] 장소 검색 추천 키워드 제공
  app/src/main/java/fc/be/app/domain/place/controller/PlaceController.java
  app/src/main/java/fc/be/app/domain/place/dto/PlacePopularKeywordsResponse.java
  app/src/main/java/fc/be/app/domain/place/service/PlaceService.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
  openapi/build.gradle
  openapi/src/main/java/fc/be/openapi/algolia/AlgoliaProperties.java
  openapi/src/main/java/fc/be/openapi/algolia/SearchEngineService.java
  openapi/src/main/java/fc/be/openapi/algolia/SearchHistory.java
  openapi/src/main/java/fc/be/openapi/tourapi/constant/ContentTypeId.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/DomainConverter.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/category/CategoryFinder.java
  openapi/src/main/resources/categories.json
  openapi/src/test/http/place.http
Labels: enhancement

#141 [Feat] 코드 및 토큰 검증 체계 변경
  app/src/main/java/fc/be/app/common/authentication/controller/AuthController.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/CheckPasswordRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/CheckTokenRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/LoginRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/ModifyLostPasswordRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/ModifyPasswordRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/RegisterMemberRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/request/SendEmailRequest.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/response/TokenResponse.java
  app/src/main/java/fc/be/app/common/authentication/exception/AuthErrorCode.java
  app/src/main/java/fc/be/app/common/authentication/exception/AuthException.java
  app/src/main/java/fc/be/app/common/authentication/manager/AbstractJwtTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/AbstractRandomKeyTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/DelegatingTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/JoinSpaceTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/ModifyTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/RegisterTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/TokenManager.java
  app/src/main/java/fc/be/app/common/authentication/model/JoinSpaceToken.java
  app/src/main/java/fc/be/app/common/authentication/model/JwtToken.java
  app/src/main/java/fc/be/app/common/authentication/model/ModifyToken.java
  app/src/main/java/fc/be/app/common/authentication/model/RandomKeyToken.java
  app/src/main/java/fc/be/app/common/authentication/model/RegisterToken.java
  app/src/main/java/fc/be/app/common/authentication/model/Token.java
  app/src/main/java/fc/be/app/common/authentication/provider/strategy/TokenGenerator.java
  app/src/main/java/fc/be/app/common/authentication/repository/RedisClient.java
  app/src/main/java/fc/be/app/common/authentication/service/AuthService.java
  app/src/main/java/fc/be/app/common/authentication/service/AuthServiceImpl.java
  app/src/main/java/fc/be/app/domain/member/dto/response/TokenResponse.java
  app/src/main/java/fc/be/app/domain/member/provider/TokenProvider.java
  app/src/main/java/fc/be/app/domain/member/provider/properties/TokenProperties.java
  app/src/main/java/fc/be/app/domain/member/service/AuthCommand.java
  app/src/main/java/fc/be/app/domain/member/service/AuthCommandHandler.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommandHandler.java
  app/src/main/java/fc/be/app/global/config/security/filter/LoginAuthenticationFilter.java
  app/src/main/java/fc/be/app/global/exception/InternalServiceErrorCode.java
  app/src/main/java/fc/be/app/global/exception/InternalServiceException.java
Labels: enhancement

#145 [Feat] 투표하기 기능 추가
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/request/VotingRequest.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VotingService.java
Labels: enhancement

#148 [Refactor] 리뷰 엔티티 응답 필드 수정
  app/src/main/java/fc/be/app/domain/member/dto/response/MyReviewsResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewCreateRequest.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewGetResponse.java
  app/src/main/java/fc/be/app/domain/review/dto/response/ReviewResponse.java
  app/src/test/java/fc/be/app/domain/review/unit/ReviewDTOFixture.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIReviewResponse.java
Labels: enhancement

#157 [Refactor/Bugfix] 리뷰 별점 산정방식 수정 및 버그 해결
  app/src/main/java/fc/be/app/domain/review/dto/RatingStatisticsDTO.java
  app/src/main/java/fc/be/app/domain/review/repository/ReviewRepository.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  app/src/test/java/fc/be/app/domain/review/unit/ReviewServiceTest.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/form/GoogleRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/service/GoogleReviewService.java
  openapi/src/main/resources/review-example/rating/place_rating_12.json
  openapi/src/main/resources/review-example/rating/place_rating_14.json
  openapi/src/main/resources/review-example/rating/place_rating_15.json
  openapi/src/main/resources/review-example/rating/place_rating_28.json
  openapi/src/main/resources/review-example/rating/place_rating_32.json
  openapi/src/main/resources/review-example/rating/place_rating_38.json
  openapi/src/main/resources/review-example/rating/place_rating_39.json
Labels: bug, enhancement

#149 [Feat] 여행스페이스 내 타이틀 변경기능 요구사항 변경 적용
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/TitleUpdateRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/CitiesResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceTokenService.java
  app/src/main/java/fc/be/app/domain/space/vo/KoreanCity.java
  app/src/main/java/fc/be/app/global/util/DelimiterConverter.java
  app/src/test/java/fc/be/app/domain/space/controller/SpaceControllerTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#153 [Feat] 투표 초기화 기능 추가
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/request/CandidateAddApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/request/CandidateDeleteApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteResultMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VotedMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/request/CandidateDeleteRequest.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#162 [Feat] 초대 링크를 이용한 space 참가 전략
  app/src/main/java/fc/be/app/common/authentication/controller/AuthController.java
  app/src/main/java/fc/be/app/common/authentication/controller/dto/response/CodeResponse.java
  app/src/main/java/fc/be/app/common/authentication/manager/AbstractJwtTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/AbstractRandomKeyTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/DelegatingTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/manager/JoinSpaceTokenManager.java
  app/src/main/java/fc/be/app/common/authentication/provider/strategy/TokenGenerator.java
  app/src/main/java/fc/be/app/common/authentication/repository/RedisClient.java
  app/src/main/java/fc/be/app/common/authentication/service/AuthService.java
  app/src/main/java/fc/be/app/common/authentication/service/AuthServiceImpl.java
  app/src/main/java/fc/be/app/common/authentication/service/VerifyService.java
  app/src/main/java/fc/be/app/common/authentication/service/VerifyServiceImpl.java
  app/src/main/java/fc/be/app/domain/member/dto/response/MySpacesResponse.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQuery.java
  app/src/main/java/fc/be/app/domain/member/service/MemberQueryHandler.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/global/config/mail/service/MailService.java
  app/src/main/java/fc/be/app/global/util/CookieUtil.java
Labels: enhancement

#165 [Feat] 여행스페이스 타이틀 관련 최종 요청사항 구현
  app/src/main/java/fc/be/app/domain/space/dto/response/CitiesResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SelectedPlaceRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/global/util/DelimiterConverter.java
  app/src/main/java/fc/be/app/global/util/ListImagesConverter.java
  app/src/test/java/fc/be/app/domain/space/entity/SpaceTest.java
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#166 [Feat] 회원 탈퇴 기능
  app/src/main/java/fc/be/app/common/authentication/exception/AuthErrorCode.java
  app/src/main/java/fc/be/app/domain/member/controller/MemberController.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/request/DeleteMemberRequest.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/request/UpdateMemberRequest.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MyInfoResponse.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MyPlacesResponse.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MyReviewsResponse.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MySpacesResponse.java
  app/src/main/java/fc/be/app/domain/member/entity/Member.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommand.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommandHandler.java
  app/src/main/java/fc/be/app/domain/member/vo/MemberStatus.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/global/config/security/DataLoader.java
Labels: enhancement

#170 [Fix] 최근 여행 스페이스 조회 시 버그 수정
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
Labels: bug

#168 [Feat] 회원가입시 Space에 참가시킨다.
  app/src/main/java/fc/be/app/domain/member/entity/Member.java
  app/src/main/java/fc/be/app/domain/member/service/MemberCommandHandler.java
  app/src/main/java/fc/be/app/global/s3/service/S3Service.java
  app/src/test/java/fc/be/app/domain/member/service/MemberCommandHandlerTest.java
Labels: enhancement

#172 [Refactor] Review Controller GET 요청 방식 수정
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/test/http/review.http
  openapi/src/test/http/review.http
Labels: enhancement

#164 [Feat] 회원은 투표하지 못한 투표 목록을 조회할 수 있어야 한다.
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepositoryCustom.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VotesResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
Labels: enhancement

#156 [Feat] 투표 요청 URL 수정
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/request/VotingApiRequest.java
Labels: enhancement

#173 [Feat] 마이페이지에 필요한 데이터 응답형식 변경
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MyInfoResponse.java
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MySpacesResponse.java
  app/src/main/java/fc/be/app/global/exception/GlobalExceptionHandler.java
Labels: enhancement

#176 [Refactor/Fix] Wish 엔드포인트 조정 및 부분 오류 수정
  app/src/main/java/fc/be/app/domain/wish/controller/WishController.java
  app/src/main/java/fc/be/app/domain/wish/dto/WishAddRequest.java
  app/src/main/java/fc/be/app/domain/wish/service/WishService.java
  app/src/main/java/fc/be/app/global/config/security/SecurityConfig.java
  app/src/test/http/wish.http
Labels: bug

#182 [Fix] Place 인접 장소 API 요청 param 추가
  openapi/src/main/java/fc/be/openapi/tourapi/dto/request/AreaBasedSync1Request.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/request/TourAPIRequest.java
Labels: enhancement

#184 [Bugfix] 스페이스가 끝난 경우 투표 목록을 가져오지 않도록 설정
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
Labels: enhancement

#185 [Feat] 여행지 등록 시 Policy 조건 추가 및 최근 여행지 조회 시 Response 변경
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/exception/SpaceErrorCode.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceTokenService.java
Labels: enhancement

#194 [Bugfix] Review Rating 방어 코드 추가
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIRatingResponse.java
  openapi/src/main/java/fc/be/openapi/google/service/GoogleReviewService.java
Labels: bug

#195 [Fix] Vote 응답 DTO 재구성 및 기능 내 결함 수정
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/space/vo/VoteStatus.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/request/VoteUpdateApiRequest.java
  app/src/main/java/fc/be/app/domain/vote/controller/dto/response/VoteUpdateApiResponse.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VotesResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/vo/SpaceInfo.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: bug

#198 [Feat] 인가 필터 적용
  app/src/main/java/fc/be/app/common/authentication/controller/AuthController.java
  app/src/main/java/fc/be/app/domain/member/controller/MemberController.java
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/wish/controller/WishController.java
  app/src/main/java/fc/be/app/global/config/security/SecurityConfig.java
  app/src/main/java/fc/be/app/global/util/JwtService.java
Labels: enhancement

#196 [Feat/Fix] 여정 여행시 삭제 기능 구현 및 FE 요구사항 적용
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/DeletedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
  app/src/main/java/fc/be/app/domain/space/dto/response/SpaceResponse.java
  app/src/main/java/fc/be/app/domain/space/entity/SelectedPlace.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/JourneyRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SelectedPlaceRepository.java
  app/src/main/java/fc/be/app/domain/space/repository/SpaceRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
Labels: enhancement

#200 [Fix] 여정의 카테고리 및 ContentTypeId 추가 전달
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceTokenService.java
  app/src/main/java/fc/be/app/global/config/WebConfig.java
  app/src/main/java/fc/be/app/global/filter/SpaceOncePerRequestFilter.java
Labels: enhancement

#202 [Fix] 누락 어노테이션 추가 및 Validation 처리
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/response/JourneyResponse.java
Labels: bug

#203 [Fix] 투표 결과보기 및 참여해야 하는 투표 조회 수정
  app/src/main/java/fc/be/app/domain/space/entity/Space.java
  app/src/main/java/fc/be/app/domain/vote/entity/Vote.java
  app/src/main/java/fc/be/app/domain/vote/entity/VoteResultMember.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteResultMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/request/CandidateAddRequest.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VoteDetailResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VoteResultResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: bug

#205 [Fix] 기존 SpaceServiceTest 제거
  app/src/test/java/fc/be/app/domain/space/service/SpaceServiceTest.java
Labels: enhancement

#208 [Fix] resource 디렉토리 생성
  .github/workflows/ci-test.yml
Labels: bug

#211 [Feat] 여행스페이스 알람 구현 및 Validation 추가
  app/src/main/java/fc/be/app/domain/notification/domain/event/vo/SpaceEventInfo.java
  app/src/main/java/fc/be/app/domain/space/dto/request/DeletedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlaceRequest.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SelectedPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/repository/JoinedMemberRepository.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceTokenService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: enhancement

#212 [Fix] Vote 쿼리 오류 수정
  app/src/main/java/fc/be/app/domain/notification/controller/NotificationController.java
  app/src/main/java/fc/be/app/domain/vote/controller/VoteControllerImpl.java
  app/src/main/java/fc/be/app/domain/vote/entity/Candidate.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteRepositoryCustomImpl.java
  app/src/main/java/fc/be/app/domain/vote/repository/VoteResultMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/repository/VotedMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/global/config/security/SecurityConfig.java
  app/src/main/java/fc/be/app/global/config/security/handler/LoginAuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/config/security/handler/OAuth2AuthenticationSuccessHandler.java
  app/src/main/java/fc/be/app/global/util/CookieUtil.java
Labels: bug

#216 [Fix] TourAPI 내 식별자 부재에 대한 처리 로직 추가
  app/src/main/java/fc/be/app/domain/member/controller/dto/response/MyPlacesResponse.java
  app/src/main/java/fc/be/app/domain/place/Location.java
  app/src/main/java/fc/be/app/domain/place/dto/PlaceInfoGetResponse.java
  app/src/test/java/fc/be/app/domain/review/unit/ReviewFixture.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/AreaBasedSyncMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/mapper/DetailCommonMapper.java
  openapi/src/main/java/fc/be/openapi/tourapi/dto/response/bone/LocationDTO.java
  openapi/src/main/java/fc/be/openapi/tourapi/tools/DomainConverter.java
Labels: bug

#220 [Bugfix] originalText null 방지 코드 추가
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIReviewResponse.java
Labels: bug

#224 [BugFix] 여행스페이스에 참가가 되지 않는 버그 및 내가 참여한 투표정보 reset 기능 버그 수정
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
  app/src/main/java/fc/be/app/domain/vote/repository/VotedMemberRepository.java
  app/src/main/java/fc/be/app/domain/vote/service/dto/response/VoteResultResponse.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteInfoQueryService.java
  app/src/main/java/fc/be/app/domain/vote/service/service/VoteManageService.java
Labels: bug

#226 [Bugfix/Style] Review Rating NPE 케이스 추가 및 코드 스타일 수정
  app/src/main/java/fc/be/app/domain/review/controller/ReviewController.java
  app/src/main/java/fc/be/app/domain/review/dto/ReviewCreateRequest.java
  app/src/main/java/fc/be/app/domain/review/service/ReviewService.java
  openapi/src/main/java/fc/be/openapi/google/dto/review/APIRatingResponse.java
Labels: bug

#228 [Fix] 여행검색 페이지에서 여행지 추가 시 오류 발생 수정
  app/src/main/java/fc/be/app/domain/space/controller/SpaceController.java
  app/src/main/java/fc/be/app/domain/space/dto/request/SearchPlacesRequest.java
  app/src/main/java/fc/be/app/domain/space/service/SpaceService.java
Labels: bug
